version: '2.1'
services:
  flask:
    restart: always
    container_name: flask_landing
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    entrypoint:
      - scripts/start.sh
    volumes:
      - .:/snailpass-landing